package mysql.Erd.shopping;
import java.io.Serializable;

/**
 * 카트 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Cart implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 주문테이블. */
	private Orders orders;

	/** 상품 테이블. */
	private Product product;

	/** 수량. */
	private Integer quantity;

	/**
	 * 생성자.
	 */
	public Cart() {
	}

	/**
	 * 주문테이블을 설정합니다..
	 * 
	 * @param orders
	 *            주문테이블
	 */
	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	/**
	 * 주문테이블을 가져옵니다..
	 * 
	 * @return 주문테이블
	 */
	public Orders getOrders() {
		return this.orders;
	}

	/**
	 * 상품 테이블을 설정합니다..
	 * 
	 * @param product
	 *            상품 테이블
	 */
	public void setProduct(Product product) {
		this.product = product;
	}

	/**
	 * 상품 테이블을 가져옵니다..
	 * 
	 * @return 상품 테이블
	 */
	public Product getProduct() {
		return this.product;
	}

	/**
	 * 수량을 설정합니다..
	 * 
	 * @param quantity
	 *            수량
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * 수량을 가져옵니다..
	 * 
	 * @return 수량
	 */
	public Integer getQuantity() {
		return this.quantity;
	}


}
